COUNTRIES = [
    'Aruba', 
    'Afghanistan', 
    'Angola', 
    'Anguilla', 
    'Albania', 
    'Aland', 
    'Andorra', 
    'United Arab Emirates', 
    'Argentina', 
    'Armenia', 
    'American Samoa', 
    'Antarctica', 
    'Ashmore and Cartier Is.', 
    'Fr. S. Antarctic Lands', 
    'Antigua and Barb.', 
    'Australia', 
    'Austria', 
    'Azerbaijan', 
    'Burundi', 
    'Belgium', 
    'Benin', 
    'Burkina Faso', 
    'Bangladesh', 
    'Bulgaria', 
    'Bahrain', 
    'Bahamas', 
    'Bosnia and Herz.', 
    'St-Barthélemy', 
    'Belarus', 
    'Belize', 
    'Bermuda', 
    'Bolivia', 
    'Brazil', 
    'Barbados', 
    'Brunei', 
    'Bhutan', 
    'Botswana', 
    'Central African Rep.', 
    'Canada', 
    'Switzerland', 
    'Chile', 
    'China', 
    "Côte d'Ivoire", 
    'Cameroon', 
    'Dem. Rep. Congo', 
    'Congo', 
    'Cook Is.', 
    'Colombia', 
    'Comoros', 
    'Cape Verde', 
    'Costa Rica', 
    'Cuba', 
    'Curaçao', 
    'Cayman Is.', 
    'N. Cyprus', 
    'Cyprus', 
    'Czech Rep.', 
    'Germany', 
    'Djibouti', 
    'Dominica', 
    'Denmark', 
    'Dominican Rep.', 
    'Algeria', 
    'Ecuador', 
    'Egypt', 
    'Eritrea', 
    'Spain', 
    'Estonia', 
    'Ethiopia', 
    'Finland', 
    'Fiji', 
    'Falkland Is.', 
    'France', 
    'Faeroe Is.', 
    'Micronesia', 
    'Gabon', 
    'United Kingdom', 
    'Georgia', 
    'Guernsey', 
    'Ghana', 
    'Guinea', 
    'Gambia', 
    'Guinea-Bissau', 
    'Eq. Guinea', 
    'Greece', 
    'Grenada', 
    'Greenland', 
    'Guatemala', 
    'Guam', 
    'Guyana', 
    'Hong Kong', 
    'Heard I. and McDonald Is.', 
    'Honduras', 
    'Croatia', 
    'Haiti', 
    'Hungary', 
    'Indonesia', 
    'Isle of Man', 
    'India', 
    'Indian Ocean Ter.', 
    'Br. Indian Ocean Ter.', 
    'Ireland', 
    'Iran', 
    'Iraq', 
    'Iceland', 
    'Israel', 
    'Italy', 
    'Jamaica', 
    'Jersey', 
    'Jordan', 
    'Japan', 
    'Siachen Glacier', 
    'Kazakhstan', 
    'Kenya', 
    'Kyrgyzstan', 
    'Cambodia', 
    'Kiribati', 
    'St. Kitts and Nevis', 
    'Korea', 
    'Kosovo', 
    'Kuwait', 
    'Lao PDR', 
    'Lebanon', 
    'Liberia', 
    'Libya', 
    'Saint Lucia', 
    'Liechtenstein', 
    'Sri Lanka', 
    'Lesotho', 
    'Lithuania', 
    'Luxembourg', 
    'Latvia', 
    'Macao', 
    'St-Martin', 
    'Morocco', 
    'Monaco', 
    'Moldova', 
    'Madagascar', 
    'Maldives', 
    'Mexico', 
    'Marshall Is.', 
    'Macedonia', 
    'Mali', 
    'Malta', 
    'Myanmar', 
    'Montenegro', 
    'Mongolia', 
    'N. Mariana Is.', 
    'Mozambique', 
    'Mauritania', 
    'Montserrat', 
    'Mauritius', 
    'Malawi', 
    'Malaysia', 
    'Namibia', 
    'New Caledonia', 
    'Niger', 
    'Norfolk Island', 
    'Nigeria', 
    'Nicaragua', 
    'Niue', 
    'Netherlands', 
    'Norway', 
    'Nepal', 
    'Nauru', 
    'New Zealand', 
    'Oman', 
    'Pakistan', 
    'Panama', 
    'Pitcairn Is.', 
    'Peru', 
    'Philippines', 
    'Palau', 
    'Papua New Guinea', 
    'Poland', 
    'Puerto Rico', 
    'Dem. Rep. Korea', 
    'Portugal', 
    'Paraguay', 
    'Palestine', 
    'Fr. Polynesia', 
    'Qatar', 
    'Romania', 
    'Russia', 
    'Rwanda', 
    'W. Sahara', 
    'Saudi Arabia', 
    'Sudan', 
    'S. Sudan', 
    'Senegal', 
    'Singapore', 
    'S. Geo. and S. Sandw. Is.', 
    'Saint Helena', 
    'Solomon Is.', 
    'Sierra Leone', 
    'El Salvador', 
    'San Marino', 
    'Somaliland', 
    'Somalia', 
    'St. Pierre and Miquelon', 
    'Serbia', 
    'São Tomé and Principe', 
    'Suriname', 
    'Slovakia', 
    'Slovenia', 
    'Sweden', 
    'Swaziland', 
    'Sint Maarten', 
    'Seychelles', 
    'Syria', 
    'Turks and Caicos Is.', 
    'Chad', 
    'Togo', 
    'Thailand', 
    'Tajikistan', 
    'Turkmenistan', 
    'Timor-Leste', 
    'Tonga', 
    'Trinidad and Tobago', 
    'Tunisia', 
    'Turkey', 
    'Taiwan', 
    'Tanzania', 
    'Uganda', 
    'Ukraine', 
    'Uruguay', 
    'United States', 
    'Uzbekistan', 
    'Vatican', 
    'St. Vin. and Gren.', 
    'Venezuela', 
    'British Virgin Is.', 
    'U.S. Virgin Is.', 
    'Vietnam', 
    'Vanuatu', 
    'Wallis and Futuna Is.', 
    'Samoa', 
    'Yemen', 
    'South Africa', 
    'Zambia', 
    'Zimbabwe'
]
